### ISSUE TITLE
how to use

### ISSUE THREAD

**Issue by coremaya** [aaa4xu/bookworm#1]

**Comment by aaa4xu** [comment]
I believe updated readme and `npm start` command should resolve your question 😃

**Comment by coremaya** [comment]
could i download pictures with it？

**Comment by aaa4xu** [comment]
Yeap

**Comment by coremaya** [comment]
> Yeap

![无标题](https://user-images.githubusercontent.com/20692119/73834269-5ccbeb80-4846-11ea-9a04-4ae3c3161248.jpg)

**Comment by aaa4xu** [comment]
You forgot execute `npm install`?

**Comment by coremaya** [comment]
Would you like to tell me how to do this? I downloaded the zip from github, and then unzipped it. I do n’t know what to do.

**Comment by aaa4xu** [comment]
`npm install`
`npm start`
should be enough

**Comment by coremaya** [comment]
> `npm install`
> `npm start`
> should be enough
![Uploading 无标题.jpg…]()

**Comment by coremaya** [comment]
> `npm install`
> `npm start`
> should be enough
![无标题](https://user-images.githubusercontent.com/20692119/73850746-3b2f2c00-4867-11ea-8aac-17c3051ab021.jpg)

**Comment by coremaya** [comment]
λ npm start                                                                                
                                                                                           
> project-bookworm@1.0.0 start D:\TOOLs\bookworm-master                                    
> node -r ts-node/register src/index.ts                                                    
                                                                                           
Error: Cannot find module '../build/Release/canvas.node'                                   
Require stack:                                                                             
- D:\TOOLs\bookworm-master\node_modules\canvas\lib\bindings.js                             
- D:\TOOLs\bookworm-master\node_modules\canvas\lib\canvas.js                               
- D:\TOOLs\bookworm-master\node_modules\canvas\index.js                                    
- D:\TOOLs\bookworm-master\src\Image.ts                                                    
- D:\TOOLs\bookworm-master\src\Page.ts                                                     
- D:\TOOLs\bookworm-master\src\Book.ts                                                     
- D:\TOOLs\bookworm-master\src\index.ts                                                    
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17)            
    at Function.Module._load (internal/modules/cjs/loader.js:686:27)                       
    at Module.require (internal/modules/cjs/loader.js:848:19)                              
    at require (internal/modules/cjs/helpers.js:74:18)                                     
    at Object.<anonymous> (D:\TOOLs\bookworm-master\node_modules\canvas\lib\bindings.js:3:1
    at Module._compile (internal/modules/cjs/loader.js:955:30)                             
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)               
    at Module.load (internal/modules/cjs/loader.js:811:32)                                 
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)                       
    at Module.require (internal/modules/cjs/loader.js:848:19)                              
npm ERR! code ELIFECYCLE                                                                   
npm ERR! errno 1                                                                           
npm ERR! project-bookworm@1.0.0 start: `node -r ts-node/register src/index.ts`             
npm ERR! Exit status 1                                                                     
npm ERR!                                                                                   
npm ERR! Failed at the project-bookworm@1.0.0 start script.                                
npm ERR! This is probably not a problem with npm. There is likely additional logging output
                                                                                           
npm ERR! A complete log of this run can be found in:                                       
npm ERR!     D:\Program Files\nodejs\node_cache\_logs\2020-02-05T14_48_14_337Z-debug.log

**Comment by coremaya** [comment]
λ npm start

> project-bookworm@1.0.0 start D:\TOOLs\bookworm-master
> node -r ts-node/register src/index.ts

Error: Cannot find module '../build/Release/canvas.node'
Require stack:
- D:\TOOLs\bookworm-master\node_modules\canvas\lib\bindings.js
- D:\TOOLs\bookworm-master\node_modules\canvas\lib\canvas.js
- D:\TOOLs\bookworm-master\node_modules\canvas\index.js
- D:\TOOLs\bookworm-master\src\Image.ts
- D:\TOOLs\bookworm-master\src\Page.ts
- D:\TOOLs\bookworm-master\src\Book.ts
- D:\TOOLs\bookworm-master\src\index.ts
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17)
    at Function.Module._load (internal/modules/cjs/loader.js:686:27)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (D:\TOOLs\bookworm-master\node_modules\canvas\lib\bindings.js:3:18)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Module.require (internal/modules/cjs/loader.js:848:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! project-bookworm@1.0.0 start: `node -r ts-node/register src/index.ts`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the project-bookworm@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     D:\Program Files\nodejs\node_cache\_logs\2020-02-05T16_15_33_527Z-debug.log

**Comment by coremaya** [comment]
npm start

> project-bookworm@1.0.0 start D:\TOOLs\bookworm-master
> node -r ts-node/register src/index.ts

Auth is detected: wunanno1@126.com
Session started
Content ID: e509bad7-174c-45b2-bb31-e29d1cb4c581
Auth data saved to ./auth.json
(node:11172) UnhandledPromiseRejectionWarning: Error: Unexpected config response status: 998
    at Function.<anonymous> (D:\TOOLs\bookworm-master\src\Book.ts:20:19)
    at step (D:\TOOLs\bookworm-master\src\Book.ts:44:23)
    at Object.next (D:\TOOLs\bookworm-master\src\Book.ts:25:53)
    at fulfilled (D:\TOOLs\bookworm-master\src\Book.ts:16:58)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
(node:11172) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:11172) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by coremaya** [comment]
please

**Comment by aaa4xu** [comment]
Look like 998 it some sort of "too frequent" error from bookwalker. It should works again in a 10-15 mins. Do you tried repeat it?

**Comment by coremaya** [comment]
> Look like 998 it some sort of "too frequent" error from bookwalker. It should works again in a 10-15 mins. Do you tried repeat it?
λ npm start                                                                                      
                                                                                                 
> project-bookworm@1.0.0 start D:\TOOLs\bookworm-master                                          
> node -r ts-node/register src/index.ts                                                          
                                                                                                 
Auth is detected: wunanno1@126.com                                                               
Session started                                                                                  
Content ID: a1cd7e3e-2230-4421-b025-dbce8225988a                                                 
Auth data saved to ./auth.json                                                                   
(node:5488) UnhandledPromiseRejectionWarning: RequestError: Error: ESOCKETTIMEDOUT               
    at new RequestError (D:\TOOLs\bookworm-master\node_modules\request-promise-core\lib\errors.js
    at Request.plumbing.callback (D:\TOOLs\bookworm-master\node_modules\request-promise-core\lib\
    at Request.RP$callback [as _callback] (D:\TOOLs\bookworm-master\node_modules\request-promise-
46:31)                                                                                           
    at self.callback (D:\TOOLs\bookworm-master\node_modules\request\request.js:185:22)           
    at Request.emit (events.js:223:5)                                                            
    at ClientRequest.<anonymous> (D:\TOOLs\bookworm-master\node_modules\request\request.js:819:16
    at Object.onceWrapper (events.js:312:28)                                                     
    at ClientRequest.emit (events.js:223:5)                                                      
    at TLSSocket.emitRequestTimeout (_http_client.js:690:9)                                      
    at Object.onceWrapper (events.js:312:28)

**Comment by coremaya** [comment]
> > Look like 998 it some sort of "too frequent" error from bookwalker. It should works again in a 10-15 mins. Do you tried repeat it?
> > λ npm start
> 
> > project-bookworm@1.0.0 start D:\TOOLs\bookworm-master
> > node -r ts-node/register src/index.ts
> 
> Auth is detected: [wunanno1@126.com](mailto:wunanno1@126.com)
> Session started
> Content ID: a1cd7e3e-2230-4421-b025-dbce8225988a
> Auth data saved to ./auth.json
> (node:5488) UnhandledPromiseRejectionWarning: RequestError: Error: ESOCKETTIMEDOUT
> at new RequestError (D:\TOOLs\bookworm-master\node_modules\request-promise-core\lib\errors.js
> at Request.plumbing.callback (D:\TOOLs\bookworm-master\node_modules\request-promise-core\lib
> at Request.RP$callback [as _callback] (D:\TOOLs\bookworm-master\node_modules\request-promise-
> 46:31)
> at self.callback (D:\TOOLs\bookworm-master\node_modules\request\request.js:185:22)
> at Request.emit (events.js:223:5)
> at ClientRequest. (D:\TOOLs\bookworm-master\node_modules\request\request.js:819:16
> at Object.onceWrapper (events.js:312:28)
> at ClientRequest.emit (events.js:223:5)
> at TLSSocket.emitRequestTimeout (_http_client.js:690:9)
> at Object.onceWrapper (events.js:312:28)

i wait for a long time，the error happened

**Comment by aaa4xu** [comment]
> > Look like 998 it some sort of "too frequent" error from bookwalker. It should works again in a 10-15 mins. Do you tried repeat it?
> > λ npm start
> 
> > project-bookworm@1.0.0 start D:\TOOLs\bookworm-master
> > node -r ts-node/register src/index.ts
> 
> Auth is detected: [wunanno1@126.com](mailto:wunanno1@126.com)
> Session started
> Content ID: a1cd7e3e-2230-4421-b025-dbce8225988a
> Auth data saved to ./auth.json
> (node:5488) UnhandledPromiseRejectionWarning: RequestError: Error: ESOCKETTIMEDOUT
> at new RequestError (D:\TOOLs\bookworm-master\node_modules\request-promise-core\lib\errors.js
> at Request.plumbing.callback (D:\TOOLs\bookworm-master\node_modules\request-promise-core\lib
> at Request.RP$callback [as _callback] (D:\TOOLs\bookworm-master\node_modules\request-promise-
> 46:31)
> at self.callback (D:\TOOLs\bookworm-master\node_modules\request\request.js:185:22)
> at Request.emit (events.js:223:5)
> at ClientRequest. (D:\TOOLs\bookworm-master\node_modules\request\request.js:819:16
> at Object.onceWrapper (events.js:312:28)
> at ClientRequest.emit (events.js:223:5)
> at TLSSocket.emitRequestTimeout (_http_client.js:690:9)
> at Object.onceWrapper (events.js:312:28)

`ESOCKETTIMEDOUT` is your internet connection problem, try again

**Comment by coremaya** [comment]
> > > Look like 998 it some sort of "too frequent" error from bookwalker. It should works again in a 10-15 mins. Do you tried repeat it?
> > > λ npm start
> > 
> > 
> > > project-bookworm@1.0.0 start D:\TOOLs\bookworm-master
> > > node -r ts-node/register src/index.ts
> > 
> > 
> > Auth is detected: [wunanno1@126.com](mailto:wunanno1@126.com)
> > Session started
> > Content ID: a1cd7e3e-2230-4421-b025-dbce8225988a
> > Auth data saved to ./auth.json
> > (node:5488) UnhandledPromiseRejectionWarning: RequestError: Error: ESOCKETTIMEDOUT
> > at new RequestError (D:\TOOLs\bookworm-master\node_modules\request-promise-core\lib\errors.js
> > at Request.plumbing.callback (D:\TOOLs\bookworm-master\node_modules\request-promise-core\lib
> > at Request.RP$callback [as _callback] (D:\TOOLs\bookworm-master\node_modules\request-promise-
> > 46:31)
> > at self.callback (D:\TOOLs\bookworm-master\node_modules\request\request.js:185:22)
> > at Request.emit (events.js:223:5)
> > at ClientRequest. (D:\TOOLs\bookworm-master\node_modules\request\request.js:819:16
> > at Object.onceWrapper (events.js:312:28)
> > at ClientRequest.emit (events.js:223:5)
> > at TLSSocket.emitRequestTimeout (_http_client.js:690:9)
> > at Object.onceWrapper (events.js:312:28)
> 
> `ESOCKETTIMEDOUT` is your internet connection problem, try again
Dose i  need a vpn
