### ISSUE TITLE
Throttling and Restart Failed Tasks

### ISSUE THREAD

**Issue by YuukixAsuna** [aaa4xu/bookworm#2]
Thanks for sharing this nice client. With the default throttling (12 pages), I was able to download ~250 pages without any problem. However, I got 403 error for the rest of the pages:

```
	[246/291] page-246.png: Failed - Error: Image downloading error: Http status code 403
    at new HttpError (/home/bzy/bookworm/src/Http/HttpError.ts:6:9)
    at Page.<anonymous> (/home/bzy/bookworm/src/Page.ts:68:19)
    at step (/home/bzy/bookworm/src/Page.ts:33:23)
    at Object.next (/home/bzy/bookworm/src/Page.ts:14:53)
    at fulfilled (/home/bzy/bookworm/src/Page.ts:5:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```
So, I modified the code and added random sleep time in each page download task and that seems to overcome this issue.

In addition, I was wondering if you can add the support to specify the start page for downloading. As you can imagine, when the download fails we would like to restart from the failed page instead of the beginning.

**Comment by aaa4xu** [comment]
Implemented a retries and reduce rpm for mitigate 403 error. Also, already downloaded pages now skips. I'm hope it helps with your case.

**Comment by YuukixAsuna** [comment]
> Implemented a retries and reduce rpm for mitigate 403 error. Also, already downloaded pages now skips. I'm hope it helps with your case.

Wow, thanks for your promote response and all those changes. Skipping the already downloaded page feature is pretty nice. Actually, I don't have objection to your previous default 'rpm'. I was wondering if the downloading can simulate the human reading behaviour so that it is more difficult to be detected by the server (we are less likely to be blocked by the server). My attempt of adding random sleep time between each downloading task is just a naive way to disguise the `client`. Do you have any better ideas in terms of obfuscating the download traffic?

**Comment by Neogrey** [comment]
@aaa4xu thanks a lot!

**Comment by aaa4xu** [comment]
@Neogrey can you give me link on this book? Can't reproduce

**Comment by Neogrey** [comment]
@aaa4xu I have this problem with all manga, for example: https://global.bookwalker.jp/de5fc8d1d3-24ed-47ab-9b72-87ff5aa14b4d/

My system:
Debian Sid
npm: 6.13.7
nodejs v10.17.0

**Comment by aaa4xu** [comment]
@Neogrey fixed

**Comment by LzNOHentai** [comment]
Thanks for your tool. But I got a error.
After I input the content ID.

`Auth data saved to ./auth.json
(node:14884) UnhandledPromiseRejectionWarning: Error:
    at new Config (f:\bookworm\src\Config.ts:23:63)
    at new Book (f:\bookworm\src\Book.ts:46:24)
    at Function.<anonymous> (f:\bookworm\src\Book.ts:26:16)
    at step (f:\bookworm\src\Book.ts:44:23)
    at Object.next (f:\bookworm\src\Book.ts:25:53)
    at fulfilled (f:\bookworm\src\Book.ts:16:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:14884) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:14884) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by aaa4xu** [comment]
@LzNOHentai can you share a link to the book? Your error is very strange and triggered only if book have wrong config on bookwalker side.

**Comment by LzNOHentai** [comment]
@aaa4xu I don't know whether your tool support Japan store.
https://bookwalker.jp/de4da7a15b-ade4-490c-9617-91952f32259a/

**Comment by aaa4xu** [comment]
@LzNOHentai yeap, Japan store is not a problem (as far as i know). But bookworm supports only manga, but your book it is ranobe.

**Comment by Jackdaw000** [comment]
Thank you for developing such a great tool.

I got the same problem as @YuukixAsuna got, I don't have any manga in my account, so I try to get a free manga to test, I download about 1/3 of the whole manga and then it starts Error 403. Sometimes I could even only download 10 of 200. I break it and try to re-download. Then I got Error 998 even though I log out and log in again. I have no idea whether it is my network's problem. My friends say my IP may be baned by Bookwalker if there is Error 998.

> Auth data saved to ./auth.json
(node:14372) UnhandledPromiseRejectionWarning: Error: Unexpected config response status: 998
    at Function.<anonymous> (C:\Users\*\Downloads\bookworm-master\src\Book.ts:22:19)
    at step (C:\Users\*\Downloads\bookworm-master\src\Book.ts:44:23)
    at Object.next (C:\Users\*\Downloads\bookworm-master\src\Book.ts:25:53)
    at fulfilled (C:\Users\*\Downloads\bookworm-master\src\Book.ts:16:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:14372) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:14372) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

The manga link is https://bookwalker.jp/de75348a8c-b1e0-4149-8bb0-559b50208e93/

I used the old version of bookworm because when I use the latest version it didn't response any more after the message below appears.

> node-pre-gyp WARN Using request for node-pre-gyp https download

My OS: Windows 10 18363.657
npm: 6.13.7
node.js v12.6.1

Thanks a lot for your developing.

**Comment by LzNOHentai** [comment]
@aaa4xu So, do you have any plan to support light novel and other books?

**Comment by aaa4xu** [comment]
@Jackdaw000 you should use latest version - it solves problem with 403 error.
> node-pre-gyp WARN Using request for node-pre-gyp https download

is not an error, and you should just wait

**Comment by aaa4xu** [comment]
> @aaa4xu So, do you have any plan to support light novel and other books in the future?

nope

**Comment by Jackdaw000** [comment]
@aaa4xu I've tried the latest version, and it is finished. Then it just quit.
After that, I open a new Windows PowerShell and use `npm start` at the folder. It start to repoet ERROR.
Here it is.

> PS D:\bookworm-master> npm start

> project-bookworm@1.1.0 start D:\bookworm-master
> node -r ts-node/register src/index.ts

D:\bookworm-master\node_modules\ts-node\src\index.ts:293
    return new TSError(diagnosticText, diagnosticCodes)
              ^
TSError: ⨯ Unable to compile TypeScript:
src/Image.ts:1:89 - error TS2307: Cannot find module 'canvas'.

1 import { CanvasRenderingContext2D, createCanvas, Image as CanvasImage, loadImage } from 'canvas';
                                                                                          
src/Image.ts:7:38 - error TS7006: Parameter 'image' implicitly has an 'any' type.

7     private script = this.image.then(image => this.createScript(this.page, image.width, image.height));      

    at createTSError (D:\bookworm-master\node_modules\ts-node\src\index.ts:293:12)
    at reportTSError (D:\bookworm-master\node_modules\ts-node\src\index.ts:297:19)
    at getOutput (D:\bookworm-master\node_modules\ts-node\src\index.ts:399:34)
    at Object.compile (D:\bookworm-master\node_modules\ts-node\src\index.ts:457:32)
    at Module.m._compile (D:\bookworm-master\node_modules\ts-node\src\index.ts:530:43)
    at Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Object.require.extensions.<computed> [as .ts] (D:\bookworm-master\node_modules\ts-node\src\index.ts:533:12)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! project-bookworm@1.1.0 start: `node -r ts-node/register src/index.ts`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the project-bookworm@1.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\\\*\AppData\Roaming\npm-cache\_logs\2020-02-21T11_17_17_394Z-debug.log

**Comment by aaa4xu** [comment]
@Jackdaw000 you have some problem with dependencies. Try to remove `node_modules` folder, execute `npm install` again in powershell and check if there any errors.

**Comment by Neogrey** [comment]
> @Neogrey fixed

Thanks for the fix.

**Comment by Jackdaw000** [comment]
@aaa4xu Thanks for your advice. I've succeed in Linux.

**Comment by Lorne0** [comment]
I still got the 998 status error, could you help me

> Auth is detected: ()
> Session started
> Content ID: 52484807-37a5-4eb1-a124-aa17f58fc1b4
> Auth data saved to ./auth.json
> (node:14878) UnhandledPromiseRejectionWarning: Error: Unexpected config response status: 998
>     at Function.<anonymous> (/home/b02902030/bookworm/src/Book.ts:22:19)
>     at step (/home/b02902030/bookworm/src/Book.ts:44:23)
>     at Object.next (/home/b02902030/bookworm/src/Book.ts:25:53)
>     at fulfilled (/home/b02902030/bookworm/src/Book.ts:16:58)
>     at processTicksAndRejections (internal/process/task_queues.js:97:5)
> (Use `node --trace-warnings ...` to show where the warning was created)
> (node:14878) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
> (node:14878) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

I ran `npm install` then `npm start`.
At the beginning I download 10 images successfully, then it ran to this error.
I've tried both in mac and ubuntu 16.04, it had same result

npm@6.14.4
node: 14.2.0

Thanks!
